apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: files-api
  name: files-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: files-api
    spec:
      containers:
      - args:
        - --spring.profiles.active=prod
        - --prod.database.url=jdbc:postgresql://$(DB_URL)
        - --prod.database.username=$(DB_USER)
        - --prod.database.password=$(DB_PASS)
        - --aws.sqs.region=eu-west-2
        - --aws.sqs.access.key=$(AWS_SQS_KEY)
        - --aws.sqs.secret.key=$(AWS_SQS_SECRET)
        - --aws.s3.region=eu-west-2
        - --aws.s3.bucket=egar-file-clean
        - --aws.s3.access.key=$(AWS_S3_KEY)
        - --aws.s3.secret.key=$(AWS_S3_SECRET)
        - --aws.s3.scanbucket=egar-file-awaiting-scan
        - --aws.s3.cleanbucket=egar-file-clean
        - --aws.s3.quarantinebucket=egar-file-quarantine
        - --egar.vscan.req.queue=develop_vscan_request
        - --egar.vscan.res.queue=develop_vscan_response
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: dburl
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: dbuser
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: dbpass
          - name: AWS_S3_KEY
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: awss3ackey
          - name: AWS_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: awss3seckey
          - name: AWS_SQS_KEY
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: awssqsackey
          - name: AWS_SQS_SECRET
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: awssqsseckey
        image: pipe.egarteam.co.uk/egar-files-api:$FILES_API_VER
        name: files-api
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 20
          httpGet:
            path: /health
            port: 8080
        resources: {}
      restartPolicy: Always
status: {}
