apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: files-api
  name: files-api
spec:
  type: NodePort
  ports:
  - name: headless
    port: 8080
  selector:
    io.kompose.service: files-api
status:
  loadBalancer: {}
